class AppStrings {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'moonCakeCalculator': 'Moon Cake Calculator',
      'addNewTask': 'Which type of moon cake would you like to make?',
      'type': 'Type',
      'cantonese': 'Cantonese-style',
      'snowSkin': 'Snow skin',
      'selectRecipe': 'Select recipe',
      'viewDetails': 'View Details',
      'fillingType': 'Filling type',
      'redBean': 'Red Bean',
      'lotusSeeds': 'Lotus Seed',
      'fiveNuts': 'Five Nuts',
      'pastryFillingRatio': 'Pastry/Filling Ratio',
      'size': 'Size (g)',
      'qty': 'Qty',
      'calculate': 'Calculate',
      'totalWeight': 'Total Weight:',
      'pastryWeight': 'Pastry Weight:',
      'fillingWeight': 'Filling Weight:',
      'goToList': 'Go to List',
      'recipes': 'Recipes',
      'addRecipe': 'Add Recipe',
      'name': 'Name',
      'style': 'Style',
      'ingredients': 'Ingredients',
      'ingredient': 'Ingredient',
      'amount': 'Amount',
      'save': 'Save',
      'cancel': 'Cancel',
      'addIngredient': 'Add ingredient',
      'recipeSavedSuccessfully': 'Recipe saved successfully.',
      'createdLocalRecipesFile': 'Created local recipes file.',
      'addAtLeastOneIngredient': 'Add at least one ingredient.',
      'failedToSaveRecipe': 'Failed to save recipe:',
      'dough': 'Dough',
      'filling': 'Filling',
      'home': 'Home',
      'tasks': 'Tasks',
      'profile': 'Profile',
      'language': 'Language',
      'english': 'English',
      'chinese': 'Chinese',
      'noRecipesFound': 'No recipes found',
      'noRecipesAvailable': 'No recipes available',
      'back': 'Back',
    },
    'zh': {
      'moonCakeCalculator': '月饼计算器',
      'addNewTask': '今天您想做哪种类型的月饼？',
      'type': '类型',
      'cantonese': '广式月饼',
      'snowSkin': '冰皮月饼',
      'selectRecipe': '选择食谱',
      'viewDetails': '查看详情',
      'fillingType': '馅料类型',
      'redBean': '红豆',
      'lotusSeeds': '莲子',
      'fiveNuts': '五仁',
      'pastryFillingRatio': '酥皮/馅料比例',
      'size': '大小 (克)',
      'qty': '数量',
      'calculate': '计算',
      'totalWeight': '总重量:',
      'pastryWeight': '酥皮重量:',
      'fillingWeight': '馅料重量:',
      'goToList': '转到列表',
      'recipes': '食谱',
      'addRecipe': '添加食谱',
      'name': '名称',
      'style': '风格',
      'ingredients': '原料',
      'ingredient': '原料',
      'amount': '数量',
      'save': '保存',
      'cancel': '取消',
      'addIngredient': '添加原料',
      'recipeSavedSuccessfully': '食谱保存成功。',
      'createdLocalRecipesFile': '创建本地食谱文件。',
      'addAtLeastOneIngredient': '至少添加一种原料。',
      'failedToSaveRecipe': '保存食谱失败：',
      'dough': '面团',
      'filling': '馅料',
      'home': '首页',
      'tasks': '任务',
      'profile': '个人资料',
      'language': '语言',
      'english': '英文',
      'chinese': '中文',
      'noRecipesFound': '未找到食谱',
      'noRecipesAvailable': '没有可用的食谱',
      'back': '返回',
    },
  };

  static String get(String key, String languageCode) {
    return translations[languageCode]?[key] ?? translations['en']?[key] ?? key;
  }
}
